export const USER_DATA = {
    About: {
        name: 'Huzaifa Anjum',
        occupation: 'FULL STACK DEVELOPER & DYNAMICS 365 CUSTOMIZER',
        details: [
            {
                title: 'Age',
                value: 23
            },
            {
                title: 'Address',
                value: 'Navi Mumbai, Maharashtra, India.'
            },
            {
                title: 'Email',
                value: 'huzaifafcrit@gmail.com'
            },
            {
                title: 'Phone',
                value: '+91 8879539141'
            }
        ]
    },
    interests: {
        title: 'Interests',
        value: [
            {
                name: 'Music',
                icon: 'headset',
                color: 'royalblue'
            },
            {
                name: 'Gaming',
                icon: 'games',
                color: 'crimson'
            },
            {
                name: 'Reading',
                icon: 'book',
                color: 'goldenrod'
            },
            {
                name: 'Sports',
                icon: 'sports_soccer',
                color: 'forestgreen'
            },
            {
                name: 'Travel',
                icon: 'flight_takeoff',
                color: 'purple'
            },
            {
                name: 'Photography',
                icon: 'photo_camera',
                color: 'grey'
            }
        ]
    }
};


export const TIMELINE_DATA = [
    {
        id: 1,
        duration: '2019 - Present' ,
        title: 'Full Satck Developer & Dynamics 365 Customizer at Willis Towers Watson' ,
        description: 'Developing and delivering production ready, enterprise grade applications which helps the organization in reducing effort, perform effeciently and save time & money. Continuosly adding new and valuable featuers and functionality to the application in each sprint. Monitoring and improving the performance of application. Also working as a D365 CRM Customizer.',
        footer : {
            licon: 'fa-building',
            lname: '1 year 1 month',
            lvalue: '',
            ricon: 'fa-certificate',
            rname: 'Certificates : ',
            rvalue: '13'
        },
        link: {
            name : 'LinkedIn',
            displayName: 'Link to LinkedIn Profile',
            value: 'https:\/\/in.linkedin.com\/in\/huzaifa-anjum-90b117133?trk=public_profile_browsemap_mini-profile_title'
        }
    },
    {
        id: 2,
        duration: '2019' ,
        title: 'Internship at Reliance Industries, developed a MEAN stack application',
        description: 'Developed a Full Stack Application which helps project managers to manage employees and projects. The application was developed using 3-tier architecture where Angular, html, css, bootstrap4 were used for front-end. Express Server and NodeJS for the middleware api and MongoDb as the database. Authentication was provided using JWT (Json Web Token). The application was made responsive in design. The application consisted of following components: home, login, register, dashboard, employee, project, report. The application was also checked on android by using an app which took URL generated by NgRok as input and loaded the application as a web View inside the app on android smartphone.',
        footer : {
            licon: 'fa-tools',
            lname: 'Projects : ',
            lvalue: '01',
            ricon: 'fa-certificate',
            rname: 'Certificates : ',
            rvalue: '01'
        },
        link: {
            name : 'Github',
            displayName: 'Link to Github Repository',
            value: 'https:\/\/github.com\/huzaifaanjum\/ProjectManagementSystem.git'
        }
    },
    {
        id: 3,
        duration: '2015 - 2019' ,
        title: 'Bachelor of Engineering - BE, Information Technology from Mumbai University',
        description: 'Graduated with a CGPA of 8.96 in Bachelor of Engineering - BE, Information Technology from Mumbai University. During the graduation period I got to work on several Projects and Mini-Projects, organized a fest, attended and conducted technical workshops for CSI and won several football tournaments.',
        footer : {
            licon: 'fa-tools',
            lname: 'Projects : ',
            lvalue: '04',
            ricon: 'fa-certificate',
            rname: 'Certificates : ',
            rvalue: '06'
        }
    },
    {
        id: 4,
        duration: '2015',
        title: 'Higher Secondary Education from Central Board of Secondary Education (CBSE)',
        description: 'Completed Higher Secondary Education from Central Board of Secondary Education (CBSE). Explored various subjects available in the field of science such as Physics, Chemistry, Mathematics and Computers. Learned to code in C and C++.',
        footer : null
    }
];
